GAME_NAME = "Spark the Electric Jester 3"
COMBAT = "Combat"
FARK = "Fark"
SFARX = "Sfarx"
SHOP_MOVES = "Shop Moves"
SHOP_POWERS = "Shop Powers"
SHOP_UPGRADES = "Shop Upgrades"
SHOP_CHARACTERS = "Shop Characters"
