GAME_NAME = "Spark the Electric Jester 3"

completion_sanities = ["base", "speedgold", "speeddia", "scoregold", "scoredia", "hunt"]

DASH = "Dash"
JESTER_DASH = "Jester Dash"
CHARGED_DASH = "Charged Jester Dash"
DOWN_DASH = "Down Dash"
WALL_JUMP = "Wall Jump"
WALL_WALK = "Wall Walk"
DOUBLE_JUMP = "Double Jump"
COMBAT = "Combat"
REAPER = "Reaper Jester"
FLOAT = "Float"
FARK = "Fark"
SFARX = "Sfarx"
CAR = "Car"
COPTER = "Copter"

SPEED_BUFF = "Speed Buff"
HYPER_SURGE = "Hyper Surge"
ENERGY_DASH = "Energy Dash"
OVERCHARGE = "Overcharge"
SNAP_PORTAL = "Snap Portal"
RADAR_SCOUT = "Radar Scout"
MULTISHOT_BLAST = "Multishot Blast"
HEAL = "Heal"
CLOUD_SHOT = "Cloud Shot"
TEMP_SHIELD = "Temp Shield"
CHARGED_SHOT = "Charged Shot"
RAIL_BOOST = "Rail Boost"
REGEN_BREAKING = "Regen Breaking"
JESTER_SWIPE = "Jester Swipe"

SHOP_MOVES = "Shop Moves"
SHOP_POWERS = "Shop Powers"
SHOP_UPGRADES = "Shop Upgrades"
SHOP_CHARACTERS = "Shop Characters"
